### ISSUE TITLE
format c-side codebase

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1144]
Due to a lull in impending c-side changes, we’d like to take the opportunity to auto-format the c-side codebase according to [the existing clang-format file](https://github.com/psi4/psi4/blob/master/.clang-format). You (and we, reviewing and merging) have until Friday, 24 Aug to get code submitted for review/merged. After that, we will be making per-module PRs of formatted changes. None of these will be merged until Wed, 29 Aug. You have until then to indicate (on the PR) that this will interrupt your development. If that happens, the PR can be closed and postponed to accommodate you. Unchallenged PRs will be merged over the week. Modules to be skipped include occ/dfocc/findif/optking/interface_dmrg because of outstanding PRs, imminent demise, or need to compare easily with upstream plugin

- [x] adc #1152
- [x] ambit_interface #1172 
- [x] ccdensity -- delay to 29 Aug #1202
- [x] ccenergy -- delay to 29 Aug #1203
- [x] cceom #1204
- [x] cchbar #1205
- [x] cclambda -- delay to 29 Aug #1206
- [x] ccresponse #1207
- [x] cctransort #1208
- [x] cctriples -- ~delay to 29 Aug (wait for #1199) #1209~ #1252 
- [x] dcft #1154
- [x] detci #1155
- [x] dfep2 #1157 
- [x] dfmp2 #1159
- [x] dfocc -- mostly done in #797, touch-ups in #1392
- [x] dmrg -- turning off formatting so can diff with plugin in CheMPS2 repo #1392
- ~findif~
- [x] fisapt #1175
- [x] fnocc #1158
- [x] gdma_interface #1166
- [x] lib3index ~#1169 (wait for #1200)~ #1389
- [x] libciomr #1173
- [x] libcubeprop -- delay to 29 Aug (wait for #1138) #1210 
- [x] libdiis #1167
- [x] libdisp #1168
- [x] libdpd -- ~delay to 29 Aug (wait for #1199) #1211~ #1251 
- [x] libfilesystem #1174
- [x] libfock ~#1164 (wait for #1224 and for @dgasmith )~ #1397
- [x] libfunctional -- ~delay to 29 Aug #1195 (wait for @dgasmith)~ #1396
- [x] libiwl #1163 
- [x] libmints -- delay to 29 Aug #1156
- [x] libmoinfo #1165
- [x] liboptions #1187
- [x] libplugin #1190
- [x] libpsi4util #1176
- [x] libpsio #1170
- [x] libpsipcm #1153
- [x] libqt #1186 
- [x] libsapt_solver & sapt #1171 
- [x] libscf_solver -- delay to 29 Aug #1194
- [x] libtrans #1162
- [x] mcscf #1189
- [x] mrcc #1161
- [x] occ #1391
- ~optking~
- [x] psimrcc #1191
- sapt (w/libsapt_solver)
- [x] `psi4/src` #1192
- [x] `psi4/include` -- will probably need selective c-f disabling for headers #1193. replaced by #1223 
- [ ] final catch-all

**Comment by loriab** [comment]
to format: `clang-format -i *.h *.cc`

to disable (for instance a data section):
```
// clang-format off
...
// clang-format on
```

**Comment by andysim** [comment]
Also, make sure you `ls` to make sure people didn't use .cpp or .CC extensions, etc.

**Comment by robertodr** [comment]
Alternatively:
```
git ls-files <folder-name>/*.{cc,h,cpp,hpp,c} | xargs clang-format -i
```
this should catch variations of file extensions.

**Comment by raimis** [comment]
Can `cctriples` and `libdpd` wait for #1199?

**Comment by raimis** [comment]
Can `lib3index` wait for #1200?

**Comment by dgasmith** [comment]
I have changes to `libfock/libfunctional`. Give me a few more weeks if possible.

**Comment by loriab** [comment]
Sure, I put X-s on them. On the other hand it'd be good get final reviews and merges on PRs w/o holds, or avoidable holds will just accumulate.

**Comment by dgasmith** [comment]
#1397 was the last holdup, this is effectively complete! I am sure smaller cleanups will continue to happen.
