### ISSUE TITLE
LGTM Day modules

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1615]
Sign up with name, check off when complete
- [ ] adc
- [ ] ambit_interface
- [x] cc/ccdensity @jeffschriber #1632
- [x] cc/ccenergy - @fevangelista #1622
- [x] cc/cceom - @fevangelista #1630
- [x] cc/cchbar @jeffschriber #1626
- [x] cc/cclambda @jeffschriber #1634
- [ ] cc/ccresponse
- [ ] cc/cctriples
- [ ] cctransort
- [x] dcft - @JonathonMisiewicz partial #1624
- [x] detci - @loriab #1631
- [x] dfep2
- [x] dfmp2 @obrien951 @derekmetcalf #1633 #1628
- [ ] ~dfocc~
- [x] dmrg
- [ ] fisapt - @zachglick 
- [ ] fnocc
- [x] gdma_interface
- [ ] lib3index @derekmetcalf #1633 #1628
- [x] libciomr #1636
- [x] libcubeprop
- [x] libdiis @derekmetcalf #1633 #1628
- [x] libdisp
- [x] libdpd @jeffschriber #1625
- [x] libfilesystem
- [ ] libfock @obrien951 #1635 
- [x] libfunctional @obrien951 #1633 #1628
- [x] libiwl
- [ ] libmints - @jturney #1616 
- [x] libmoinfo - @fevangelista #1617
- [ ] liboptions - @loriab #1621
- [x] libplugin
- [x] libpsi4util
- [x] libpsio - @fevangelista #1618
- [x] libpsipcm
- [x] libqt @jeffschriber #1619
- [x] libsapt_solver @zachglick @dsirianni #1623
- [x] libscf_solver @JonathonMisiewicz #1629
- [x] libtrans @JonathonMisiewicz #1627
- [ ] ~mcscf~
- [x] mrcc
- [ ] ~occ~
- [ ] ~optking~
- [x] psimrcc
- [x] sapt @zachglick 
- [x] scfgrad @alenaizan #1620
- [x] core #1636

changing type to `size_t`
* `BasisSet.nbf_` int --> size_t
* `Wavefunction.nso_` int --> size_t

**Comment by JonathonMisiewicz** [comment]
Example of fixing the dreaded "Multiplication result may overflow 'int' before it is converted to 'size_t'."
Replace
```
    nElements += R.params->coltot[h] * R.params->rowtot[h];
```
with
```
    nElements += static_cast<size_t>(R.params->coltot[h]) * R.params->rowtot[h];
```

**Comment by loriab** [comment]
lib3index Derek & Joe
libqt Jeff
scfgrad Asim
libsapt_solver Zach
moinfo fevange
libmints jturney
liboptions loriab


`static_cast<size_t> (var)`

**Comment by loriab** [comment]
Jet has a model for "No matching copy assignment operator in class Data. It is good practice to match a copy constructor with a copy assignment operator." in #1616

**Comment by loriab** [comment]
-[x] lib3index
-[ ] dfmp2 Joe & Derek

**Comment by jeffschriber** [comment]
- [X] libqt
- [ ] libdpd Jeff

**Comment by dsirianni** [comment]
- [ ] libsapt (start from top)

**Comment by derekmetcalf** [comment]
- [x] dfmp2
- [x] libfunctional
- [ ] libdiis

**Comment by JonathonMisiewicz** [comment]
`mcscf` removed from the list, per plans to eliminate it discussed with @fevangelista. Moving on to libtrans.

**Comment by JonathonMisiewicz** [comment]
The time of LGTM is passed, so closing.
