### ISSUE TITLE
Documentation maintenance for 1.4

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#2109]
_This is a meta-issue and will be updated as needed._

- [ ] open issues:
  - [ ] #2105  (Molecule reading)
  - [ ] #1769 (document linear response features)
  - [ ] #1678 (orbital guess)
  - [ ] #1341 (outdated, but maybe similar for libint2)
  - [ ] #2108 (td-dft example)
- [ ] cross-check with (final) release notes if all features are documented/mentioned.
- [ ] Run every example input in the manual once a release candidate is ready.
 
Please add `documentation` as label for relevant new or old issues so they can be easily found.
https://github.com/psi4/psi4/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation
