### ISSUE TITLE
Fails to find libint2

### ISSUE THREAD

**Issue by yurivict** [psi4/psi4#2398]
1.5 fails to find libint2-2.7.1:
```
-- Could NOT find Libint2 (missing: Libint2_DIR)
-- Suitable Libint2 could not be located, Building Libint2 5-4-3-6-5-4 instead.
```

Adding ```-DLibint2_DIR=/usr/local``` doesn't change anything.

**Comment by loriab** [comment]
Are you trying to use a Libint2 release? Keep in mind that Psi4 needs changes to the upstream buildsystem (these can be worked around) and changes to the default upstream build configuration (such that a built library won't work with any other open-source QC package). I'll collect some links here since it's worth having an issue open on this for packagers to consult (hence pinging @mbanck, @susilehtola).

* https://github.com/psi4/psi4/issues/2300 (search "multidimensional") for background and conda-forge
* https://github.com/evaleev/libint/issues/190 for the general open-source conundrum and current psi4 prospects toward the end
* https://github.com/psi4/psi4/blob/master/external/upstream/libint2/CMakeLists.txt#L1-L25 for libint2 build constraints for Psi4

Steps toward Psi4 using a upstream Libint2 release in common with other open-source QC programs:
- [x] transition psi4 TEI #1721
- [ ] reconcile LAB's l2 cmake (that psi uses at present) https://github.com/loriab/libint/tree/l2cmake with EFV's adaptations https://github.com/evaleev/libint/pull/205
- [ ] merge https://github.com/evaleev/libint/pull/205 and release
- [ ] expand current integrals config requirements beyond current set in notes (needed before #2388)
- [ ] transition psi4 OEI #2388 
- [ ] transition psi4 integral ordering from `gss` to `sss`
- [ ] coordinate with packagers and other QC programs for a AM and integrals types l2 config options set that is adequate for all

If I'm off base @yurivict and you're already using a psi-configured l2 and this is simply a detection issue, let me know.

**Comment by yurivict** [comment]
You also have ```find_package(Libint ...)``` that can't work because libint2 doesn't provide cmake files, and you don't provide them either.

**Comment by loriab** [comment]
> You also have find_package(Libint ...) that can't work because libint2 doesn't provide cmake files, and you don't provide them either.

The  https://github.com/loriab/libint/tree/l2cmake branch provides the config file https://github.com/loriab/libint/blob/l2cmake/cmake/Libint2Config.cmake.in via either the repo or the tarballs https://github.com/psi4/psi4/blob/master/external/upstream/libint2/CMakeLists.txt#L57-L70 . If you're not familiar with l2, you'll want to familiarize with the build stages of a cmake+cmake build https://github.com/loriab/libint/blob/l2cmake/CMakeLists.txt#L26-L44 . One can use a libtool+cmake build but then you have to disable `find_package` according to my notes above, particularly https://github.com/psi4/psi4/blob/master/external/upstream/libint2/CMakeLists.txt#L14-L15 .

**Comment by mbanck** [comment]
> You also have `find_package(Libint ...)` that can't work because libint2 doesn't provide cmake files, and you don't provide them either.

libint2 does (or at least can) provide cmake files, even with the 2.6.x releases, but it's somewhat tricky.

I don't think anything besides psi4 uses them, and for psi4 they are broken/much bigger issues (see above).

As I mentioned in https://github.com/evaleev/libint/issues/190#issuecomment-1003936604 libint2 (experimental Debian 2.7.1 package) gets detected fine, but there are build errors later on.
