### ISSUE TITLE
Excited State Variable Cleanup

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2486]
This is the mega-issue for the cleanup of excited-state variables. I come to this as a spinoff of the cc modernization mega-issue, which is a spin-off of the density sanitizing mega-issue. The goal of this mega-issue is to synchronize variable names across TDDFT, EOM, and ADC, per the standard introduced in #2462 and amended slightly in #2475.

### The Standard
We support the following access patterns:
```
    f"{method} ROOT 0 ({initial_state}) -> ROOT {irrep_idx} ({target_state}) EXCITATION ENERGY"
    f"{method} TD-HF ROOT 0 -> ROOT {global_idx} EXCITATION ENERGY
    f"{method} ROOT 0 -> ROOT {global_idx} EXCITATION ENERGY - {transition} TRANSITION
```

- `{method}` should include both the _family_ of the method and the _specific method_ used. For example, both `CC` and `CC3`.
- `{global_idx}` is the index of the root, ordered by energy, in the space of all roots.
- `{irrep_idx}`is the index of the root, ordered by energy, in the space of roots of that irrep. This should **never** be larger than `global_idx` and is identical `global_idx` for molecules without symmetry.
- `{initial_state} ^ {target_state} = {transition}`

### The Status

- [x] DFT
  - [x] #2462 - initial cleanup
  - [x] (part of) #2477 - set TD-DFT variables with names starting TD-SCF or TD-DFT (maybr both?) in addition to TD-fctl
- [ ] EOM
  - [x] #2475 - variables set directly in `cceom`
  - [x] Variables set directly in `ccdensity`
    - [x] #2514 - Oscillator strengths
    - [x] #2525 - Einstein coefficients, rotation strengths
    - [x] #2538 - All access patterns  
  - [ ] Variables set indirectly, via oeprop
    - [X] #2479 - remove mutlipole component variables from being set in oeprop
    - [x] #2485 - condense multipole setting functions into one
    - [ ] #2541 Rename multipole variables from `oeprop` according to the standard
- [x] ADCC
  - [x] #2513 
- [ ] Final cleanup pass
