### ISSUE TITLE
The developer wish list

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#402]
This is a list of things that are generally agreed as "good things to do", but nobody has actually tackled yet. The hope is that this is used a central repository of "have you thought about this" comments. Note that this is a not a feature wish list.

## High 
- [ ] Deprecate PSIO by moving to HDF5. With a temporary under the hood PSIO move to HDF5.
- [ ] Remove `boost::python` and replace with PyBind11.
- [ ] Possibly remove Boost with C++11 features. Std managed pointers are high on the list.
- [ ] Switch Psi4 from a binary to a library
    - [ ] Allow more flexible external libraries
- [ ] Remove C-side python calls. DFT-D3, DFT functionals, BasisSet parsing, etc.
- [ ] Add a dictionary to the Wavefunction object thats holds the current Psi Variables.
- [ ] Flip Psi4 so that it is no longer a binary, but a python library

## Medium
- [ ] Rewrite LibOptions as a property map or just a general dictionary. Needs to be more object oriented, less global, and capable of encompassing all QCDB.
- [ ] Full Python3 support. This is mostly done, but small sections are not Python3 compatible.
- [ ] Ability to combine fitting sets via partial decomposition of a expanded Coulomb metric.
- [ ] ECP would be a great addition.

## Low
- [ ] More flexibility in compilation of integrals. For example compiling 3-index and Coulomb metric integrals at a higher AM than the conventional basis set.
- [ ] 4th CMake rewrite. Currently overly cautious about what needs to be recompiled.

Modify, expand, delete as desired. If you take up a feature make sure to post here so that we do not duplicate effort.

**Comment by jgonthier** [comment]
## Medium ##

[ ] Parallelize the mints integral generation:
Needs to use asynchronous I/O to have one process writing to disk while others compute. Basic technology to do that is in the new PKJK object.

[ ] Reduce PKJK I/O
Preliminary experiment shows that storing only the ordered supermatrix for J and reordering it on the fly when forming K is faster than I/O for storing/reading ordered supermatrix for K.

[ ] Sieve PKJK 
Currently PKJK only uses sieving for integral computations. Could use it to only I/O significant integrals. We would probably need a specialized iterator that goes only through significant integrals and gives us back the absolute indices for building J and K.

**Comment by jgonthier** [comment]
## Medium ##

- [ ] Design and implement a memory manager

**Comment by loriab** [comment]
Purportedly, @bennybp has a memory manager in pulsar.

**Comment by loriab** [comment]
Moved from #476 so as to not clutter issues.

* [ ] Here lie uses for general Cholesky machinery.

  * [ ] Fock-type terms in DF-SAPT, particularly higher-order, see #317 
  * [ ] If you care about 6-zeta accuracy, you probably oughtn't to be using density fitting. Nevertheless, having orbital basis sets for which _no_ auxiliary is appropriate (even as overkill, like QZ for sto-3g) is troubling for the auxiliary defaulting machinery. On-the-fly construction could help. Maybe a more plausible case is when auxiliary basis sets aren't available for a particular element or for tight functions.

Moreover, Susi Lehtola comments:

Well, you could do compact atomic Cholesky to construct a fitting basis for an arbitrary orbital basis set on-the-fly. [doi 10.1063/1.3116784]

**Comment by loriab** [comment]
@CDSherrill requests a disk use estimate. Could just be final disk use as a system call before cleaning (https://github.com/psi4/psi4/blob/master/psi4/run_psi4.py#L196).

**Comment by CDSherrill** [comment]
Yes, this would be very helpful so that users will know how much disk is
needed (even approximately) for subsequent jobs of this type.  It is also
helpful to people planning to buy new hardware and who need to know how
much disk to buy.... one can look back through old outputs on some of the
challenging computations and see how much disk they used.

**Comment by susilehtola** [comment]
detci memory size checks would be nice. Signed, someone who has crashed his computer a few times by trying to do a too big calculation.

**Comment by loriab** [comment]
- [ ] Implement logging for PsiAPI mode so that output files (currently w/o Psi4 header or any record of input commands or options) aren't so mysterious. At minimum, print to output the `psi4.header()` at file creation and e.g. `>>> aggh = psi4.energy("scf")` and `>>> psi4.set_options({"scf_type": "pk"})`  to track what was done.

**Comment by loriab** [comment]
- [ ] API-like loading of basis sets. If one has the coef and the exp, shouldn't have to write them out to a .gbs, should be a constructor to take them directly.

**Comment by loriab** [comment]
* [ ] Adapt CC* modules to take in Wfn so that truncated virtual space proceeds transparently. Feature request (http://forum.psicode.org/t/rvs-approximations-for-cc2-or-adc-2/504)

**Comment by loriab** [comment]
- [ ] Matt Schieber has info on KMP affinity and thread binding schemes that hurt and help performance. See if the one that helps can be encoded at runtime (knowing some /proc/cpuinfo) or otherwise advise in docs.

**Comment by susilehtola** [comment]
- [ ] CISD module should be able to compute density matrices, so that the NOs could be used as initial guesses for detci

**Comment by loriab** [comment]
- [ ] 

```
sp = single_point('scf')
sp.compute() # ?
wfn = sp.wfn()
energy = sp.energy()
```

**Comment by susilehtola** [comment]
- [ ] Implement O2 method, i.e. orbital-optimized scaled opposite-spin MP2 [R. C. Lochan and M. Head-Gordon, J. Chem. Phys. 126, 164101 (2007)].

**Comment by susilehtola** [comment]
- [ ] Implement exchange guess for virtual orbitals for CI calculations. (Improved virtual orbitals by rediagonalizing virtual space with respect to exchange operator.)

**Comment by loriab** [comment]
- [ ] Unify origin-setting for properties/integrals. Properties by oeprop get their origin from options (https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/oeprop.cc#L775-L808). Mints integrals get their origin from default 0,0,0 or from options. But with Mints, you sometimes want to set the origin by argument (default 0,0,0) in API. Unification so that useful from both input file and API would be nice. Also maybe an easy center-of-charge spec.

**Comment by loriab** [comment]
- [ ] Can libmints get away with not having `MAX_AM_ERI` passed to it? That way one could switch out `libint.so`s on the fly (conda can do this). Would have to find a way to still exit gracefully if insufficient AM and give decent error messages.

**Comment by loriab** [comment]
- [ ] Examine `properties` function in driver (that encodes the extended workflows beyond sp or time-trivial keyword needed to compute CC properties) and the `oeprop` syntax that most all other methods use.  Devise and implement a unified interface that still works with the code.

**Comment by robertodr** [comment]
- [ ] Add FCIDUMP capabilities within Psi4. There are currently many third-party plugins that do that and it seems needed enough to have it within the main code.

**Comment by loriab** [comment]
### Beginner-Friendly (after py-side SCF)

Renovate SCF damping capabilities
- [ ] right now we're only damping `D`. There are rumors that should also damp `F` or there's an iteration mismatch between `D` & `F`. Make sure damping is working right (presently only test case is scf-coverage and damping severely _hurts_ convergence
- [ ] right now we damp to the very end of iterations. Maybe damp only to 1e-4 (after which soscf might be better choice, now that DGAS has implemented) controlled by DAMPING_CONVERGENCE.
- [ ] here's a paper with potentially useful schemes https://arxiv.org/pdf/1302.6099.pdf
- [ ] consider (this may be separate project) more advanced driver logic. perhaps something along the lines of (DGAS) "Damp first iteration, then DIIS, if density is stuck take stability step, if grad < 1.e-4 and target < 1.e-8 take SOSCF, else DIIS. if density oscillation (dRMS/oscilation) > 1.e2 add damping"

**Comment by susilehtola** [comment]
Related to @loriab 's previous comment... damping F is a lot more better than damping D, since instead of intrapolating inside a fixed Hilbert space of density, you're actually looking at different densities. You converge faster if you damp F than if you just damp D, and you're less likely to land on a saddle point.

**Comment by loriab** [comment]
Make use of doublet/triplet c-side. In particular, https://github.com/psi4/psi4/pull/737/files#r121282237

**Comment by loriab** [comment]
#### things we can do after dumping py27 (just to keep track)

- [ ] delete all `__future__` statements
- [ ] simplify molutil and qcdb/molecule.py raw_* functions

**Comment by loriab** [comment]
[from @dgasmith psi4/psi4#928 ] File names are going haywire a bit with different conventions for either PSIO or "user facing names" like Molden and cube files. Anyone have a good idea how to rectify this? It would also be good to have restart work for gradients, Hessians, and properties as well. Ill add this to the wish ilst.

**Comment by j3mdamas** [comment]
As per discussed with @loriab in https://github.com/psi4/psi4/issues/933, it would be interesting to have a Windows native compilation for psi4

**Comment by loriab** [comment]
Possible easy-start issues
- [ ] rVV10, [comments starting here](https://github.com/psi4/psi4/pull/914#issuecomment-364765089)
- [ ] Wigner tunneling correction, [comments](https://github.com/psi4/psi4/pull/834#discussion_r165244581)
- [ ] Grimmer low-freq vib correction

**Comment by robertodr** [comment]
- [ ] PCM gradients _à la_ [ECP](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L2108-L2145), whereby the _in vacuo_ terms are computed analytically and the PCM terms numerically. This can actually be done already on top of #953. Of course, it would be good to have it fully analytic. That's more of a PCMSolver-side problem and a time investment I can't currently make. For those interested, there is this (very broken) PCMSolver/pcmsolver#140 which should make much easier implementing the cavity terms for the gradient and Hessian.

**Comment by loriab** [comment]
So we don't forget it

- [ ] https://github.com/psi4/psi4/pull/1075#discussion_r203034758

**Comment by JonathonMisiewicz** [comment]
Have findif intercept and rerun suspect SCFs. Definitely wait for this until after findif is accepted, findif is converted from list based to dict based (so we can store SCF at the displacement as metadata) and we have some preliminary smart SCF.

**Comment by loriab** [comment]
- [ ] `PSIO_REMOVE_FILE`/ `PSIO_KEEP_FILE`? from #1310 
- [ ] matrix copy issue https://github.com/psi4/psi4/pull/1267/files#r228203247

**Comment by loriab** [comment]
- [ ] `-D(abc)` work needs to continue, see https://github.com/psi4/psi4/pull/1151#issuecomment-417101476 and below
- [ ] add named per-parameter access to DFT functionals now that we can get names from libxc

**Comment by JonathonMisiewicz** [comment]
For findif computations, have the preliminary displacements needed to compute the gradient be funneled into the frequency displacements.

**Comment by loriab** [comment]
- [ ] beta orbitals in mo extents
- [ ] mo polarity https://github.com/psi4/psi4archive/commit/d337912cc48fe14aa8ae78820581fc8f0495383a

**Comment by susilehtola** [comment]
* possibility to override charge states of individual atoms in SAD guess

**Comment by loriab** [comment]
been adding some things that are correct but not full-stack hooked up. here are the reminders to do so:
- [ ] after #1491, add the ability to call ATM from functional., e.g. `energy('b3lyp-d3-atm`)`
- [ ] after #1491, MP2D gradients still need addressing
- [ ] after #1490, set up a `energy(sapt0inf)` call (if component anaylysis deems suitable) and add it to the qcvar parade. Also, figure out why it's only in fisapt and is called through dft-sapt.

**Comment by loriab** [comment]
save one-electron ints in wfn so that (1) not writing to disk, thus freeing SCF from disk and thread-safety issues, and (2) better carry around external potentials btwn modules.

**Comment by loriab** [comment]
- [ ] dft functionals in https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/dft/libxc_functionals.py pull all their citation metadata from libxc, thus avoiding duplicated work. Functionals that need separate X & C from libxc currently have metadata redefined in psi. Change this so that where X & C pulled separately from libxc have the same citation, this gets adopted as total citation. discussed a bit in https://github.com/psi4/psi4/pull/1597

**Comment by loriab** [comment]
- [ ] Investigate [Susi comment](https://github.com/psi4/psi4/pull/1499#issuecomment-497468619) on possible advantages for ints screening if we switched the arithmetic for omega functionals.

**Comment by susilehtola** [comment]
[ ] Implement potential-based orbital projection as described in [Chem Phys Lett 531, 229 (2012)](http://dx.doi.org/10.1016/j.cplett.2012.02.012). The main problem is that one needs cross-basis Coulomb and exchange integrals (IJ|kl) and (Ik|Jl) where IJ are in the new, large basis and kl are in the small input basis. For DFT, the density variables would be evaluated in the small basis, and the quadrature would be done in the new basis.

**Comment by loriab** [comment]
- [ ] MemJK disk algorithm therein could have omega thrown in. background in https://github.com/psi4/psi4/pull/1749

**Comment by susilehtola** [comment]
- [ ] seminumerical exchange engine. [doi:10.1021/acs.jctc.9b00860](https://pubs.acs.org/doi/10.1021/acs.jctc.9b00860) shows a 10x speedup over LinK

**Comment by hokru** [comment]
- [ ] direct DF-J/K integral generation for better parallel scaling.

**Comment by loriab** [comment]
- [ ] @jturney found https://github.com/pybind/pybind11_json to convert python dict to nlohmann's json library. could be useful for qcsk <-> psi4.core.BasisSet roundtripping and options conversion

**Comment by TiborGY** [comment]
- [ ] Replace all `__FILE__`, `__LINE__` and `__PRETTY_FUNCTION__` macros with `std::source_location` when Psi4 transitions to C++20 minimum requirement

**Comment by TiborGY** [comment]
- [ ] Beyond just debug/release CMake build type, have a "profiling" build where both debugging and optimization are enabled. This is required if one wants to run perf/Vtune and get meaningful results. With modern compilers the debugging symbols contain enough information that compiler optimizations do not make debugging/profiling impossible.
- [ ] Investigate the possibility of building everything with LTO. Possible benefits: smaller binary sizes, performance improvement, unused functions are automatically stripped.

**Comment by hokru** [comment]
> * Beyond just debug/release CMake build type, have a "profiling" build where both debugging and optimization are enabled. This is required if one wants to run perf/Vtune and get meaningful results. With modern compilers the debugging symbols contain enough information that compiler optimizations do not make debugging/profiling impossible

Before making a custom option, perhaps `RelWithDebInfo` is enough?

**Comment by loriab** [comment]
CD gradient tech. @JonathonMisiewicz located some papers: https://aip.scitation.org/doi/10.1063/5.0087261 and https://onlinelibrary.wiley.com/doi/10.1002/qua.24563

**Comment by davpoolechem** [comment]
Some things to add to the wishlist from my end:

- [ ] Update COSX to support arbitrary grids via modification of X-matrix handling (see https://github.com/psi4/psi4/issues/2890 for further details).
- [ ] Add CFMM and/or DF-CFMM to Psi4 officially. These already exist in Psi4 development branches, but need to be updated to match modern Psi4 developments (e.g., current formulations of CompositeJK) and actually put into Psi4. The first PR for these methods already exists (https://github.com/psi4/psi4/pull/2665).
- [ ] Support for [J-Engine](https://doi.org/10.1063/1.470986). J-Engine is a nice algorithm by the Head-Gordon group to help reduce the prefactor of J-build calculations via reformulation of how integral intermediates are formed and contracted with the density matrix to form Coulomb matrix elements. As it deals with shuffling around how integral intermediates are formed and combined with the density, any J-Engine effort will likely require coordination with the Valeev group and development within Libint2 itself (although the Valeev group did seem interested in J-Engine from what discussions I had with their researchers).
