### ISSUE TITLE
wind down psi4/psi4private

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#508]
At the last developers' workshop, we decided to close the longstanding psi4/psi4private repo. However, first we want to make sure we're not losing any good info. The Plan is below. People mentioned need to sign off on the deletion of branches or the closing of issues.

- [ ] clear away old branches
  - no commits ahead
    - [ ] [ccenergy](https://github.com/psi4/psi4private/tree/ccenergy)
    - [ ] [cctransort](https://github.com/psi4/psi4private/tree/cctransort)
    - [ ] [rhf_ccsd_t_gradient](https://github.com/psi4/psi4private/tree/rhf_ccsd_t_gradient)
    - [ ] [ccwavefunction](https://github.com/psi4/psi4private/tree/ccwavefunction)
    - [ ] [roa](https://github.com/psi4/psi4private/tree/roa)
    - [ ] [eom_overlap](https://github.com/psi4/psi4private/tree/eom_overlap)
    - [ ] [optking](https://github.com/psi4/psi4private/tree/optking)
    - [ ] [ccs](https://github.com/psi4/psi4private/tree/ccs)
    - [ ] [higher_level_dcft](https://github.com/psi4/psi4private/tree/higher_level_dcft)
    - [ ] [newbasis](https://github.com/psi4/psi4private/tree/newbasis)
    - [ ] [broken_code](https://github.com/psi4/psi4private/tree/broken_code)
    - [ ] [onetep](https://github.com/psi4/psi4private/tree/onetep)
  - [x] [USAPT](https://github.com/psi4/psi4private/tree/USAPT) @jgonthier 
  - [ ] [psi4sofix](https://github.com/psi4/psi4private/tree/psi4sofix) @bennybp
  - [ ] [fancy_opts](https://github.com/psi4/psi4private/tree/fancy_opts) @bwb314 
  - [x] [roberto/alt-VPCM](https://github.com/psi4/psi4private/tree/alt-VPCM) @robertodr 
  - [x] [VPCM](https://github.com/psi4/psi4private/tree/VPCM) @robertodr 
  - [x] [ambit](https://github.com/psi4/psi4private/tree/ambit) @jturney 
  - [x] [Rob-pcm](https://github.com/psi4/psi4private/tree/Rob-pcm) @robertodr 
  - [ ] [andysim](https://github.com/psi4/psi4private/tree/hessians) @andysim 
  - [x] [USAPT_parallel](https://github.com/psi4/psi4private/tree/USAPT_parallel) @jgonthier 
  - [x] [PsiAPI](https://github.com/psi4/psi4private/tree/PsiAPI) @ryanmrichard 
  - [x] [pcm_ccsd](https://github.com/psi4/psi4private/tree/pcm_ccsd) @robertodr 
  - [ ] [dcft_erpa](https://github.com/psi4/psi4private/tree/dcft_erpa) @avcopan 
  - [ ] [bennyp-efp](https://github.com/psi4/psi4private/tree/bennyp-efp) @bennybp 
  - [ ] [sim_local](https://github.com/psi4/psi4private/tree/sim_local) Ashutosh Kumar
  - [x] [p4orca](https://github.com/psi4/psi4private/tree/p4orca) @loriab
  - [x] [GTFock2](https://github.com/psi4/psi4private/tree/GTFock2) @ryanmrichard 
  - [x] [pcm](https://github.com/psi4/psi4private/tree/pcm) @robertodr 
  - [ ] [nbody](https://github.com/psi4/psi4private/tree/nbody) @mactay 
  - [x] [psiworkweek](https://github.com/psi4/psi4private/tree/psiworkweek) @loriab
  - [x] [gtfock](https://github.com/psi4/psi4private/tree/gtfock) @ryanmrichard 
  - [x] [pcm-detci_corr-only](https://github.com/psi4/psi4private/tree/pcm-detci_corr-only) @robertodr 
  - [x] [pcm-detci](https://github.com/psi4/psi4private/tree/pcm-detci) @robertodr 
  - [x] [pcm-triples](https://github.com/psi4/psi4private/tree/pcm-triples) @robertodr 
  - [x] [c4](https://github.com/psi4/psi4private/tree/c4) @loriab
  - [ ] [nto](https://github.com/psi4/psi4private/tree/nto) @harls 
  - [ ] [ash_fno](https://github.com/psi4/psi4private/tree/ash_fno) Ashutosh Kumar
  - [ ] [ecp](https://github.com/psi4/psi4private/tree/ecp) @edeprince3 
  - [ ] [dfcc](https://github.com/psi4/psi4private/tree/dfcc) @andysim 
  - [ ] [gfmm_cfmm](https://github.com/psi4/psi4private/tree/gfmm_cfmm) @bill-march
  - [x] [asapt](https://github.com/psi4/psi4private/tree/asapt) @robparrish 
  - [ ] [xtd](https://github.com/psi4/psi4private/tree/xtd) @harls 
  - [ ] [cc](https://github.com/psi4/psi4private/tree/cc) @andysim 
  - [x] [clean_python](https://github.com/psi4/psi4private/tree/clean_python) @loriab
  - [ ] [gfmm_jk](https://github.com/psi4/psi4private/tree/gfmm_jk) @bill-march
- [ ] clear away old tickets
  - **close** 
    - [ ] psi4/psi4private#8
    - [ ] psi4/psi4private#11 
    - [ ] psi4/psi4private#21 
    - [ ] psi4/psi4private#39 
    - [ ] psi4/psi4private#51 
    - [ ] psi4/psi4private#61 (after @robparrish signs off)
    - [ ] psi4/psi4private#79 (after @edeprince3 signs off) 
    - [x] psi4/psi4private#110
    - [x] psi4/psi4private#120 (after @dgasmith extract anything important into devel wishlist)
  - move to **developers wishlist** copying any good links or comments 
    - [ ] psi4/psi4private#5 
    - [ ] psi4/psi4private#6 
    - [ ] psi4/psi4private#13 
    - [ ] psi4/psi4private#14 
    - [ ] psi4/psi4private#18 
    - [ ] psi4/psi4private#46 
    - [ ] psi4/psi4private#50 (keep the link) 
    - [ ] psi4/psi4private#53 
    - [ ] psi4/psi4private#57 
    - [ ] psi4/psi4private#74
  - **new ticket in psi4/psi4**
    - [ ] psi4/psi4private#3 (hit a psio error trying to confirm-or-deny. will try to make gists public)
    - [ ] psi4/psi4private#16 
    - [ ] psi4/psi4private#20 
    - [ ] psi4/psi4private#54 
    - [ ] psi4/psi4private#75 + psi4/psi4private#92
- [x] repost as a public psi4/psi4betas repo with branches:
  - [x] `4.0b1`
  - [x] `4.0b2`
  - [x] `4.0b3`
  - [x] `4.0b4`
  - [x] `4.0b5`
  - [x] `1.0`

**Comment by dgasmith** [comment]
Seems like 16, 20, 54, 75, 92 are wishlist features?

**Comment by loriab** [comment]
esp. 16 & 20 seemed close enough (docs & test McGibbon's resp plugin) to be tickets in their own right. but feel free to edit.

**Comment by ryanmrichard** [comment]
feel free to kill my branches

**Comment by jgonthier** [comment]
Feel free to kill my branches as well. USAPT has been merged into the public and USAPT_parallel was only a draft that I backed up on my end already.

**Comment by robertodr** [comment]
I have backed up the whole private repository. I have also closed psi4/psi4private#110

**Comment by loriab** [comment]
Thanks, @robertodr, does that mean all your branches can be checked off here?

**Comment by robertodr** [comment]
Yes, they can all be ticked off. Sorry for not being more explicit.

**Comment by dgasmith** [comment]
It doesnt look like there is a huge impetus to close this down so were just going to leave `psi4/psi4private` up. However, note that these branches are no longer valid due to the many changes and history rewriting since they have been edited. All history `psi4private` history (but not the dev branches) will be public [here](https://github.com/psi4/psi4archive).
